alias rc="source ~/.zshrc"
alias c="clear"
alias k="kubectl"
alias kctx="kubectl ctx"
alias kns="kubectl ns"
alias tf="terraform"
alias commit="git rev-parse --short HEAD"
alias gri="git rebase --interactive"
alias gp="git push"
alias gpf="git push --force"
alias gs="git stash"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gres="git checkout main && git pull --rebase"
alias mres="git checkout master && git pull --rebase"
alias gsa="git stash apply"
alias dev="ssh sa-luke.muccillo@syd-it-vl016"
