FROM ubuntu:24.04

RUN apt update
# Install my shell
RUN apt install -y git ninja-build gettext cmake unzip curl build-essential

# Install requirements for nvim build
WORKDIR /tmp

RUN git clone --branch release-0.10 --single-branch https://github.com/neovim/neovim.git

WORKDIR /tmp/neovim
RUN make CMAKE_BUILD_TYPE=Release
RUN make install

# Create my user
RUN useradd -ms /usr/bin/zsh me
# Set workdir to my home directory
USER me
WORKDIR /home/me

# Install rust so that we can use rust tools
ENV PATH="/home/me/.cargo/bin:${PATH}"
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source ~/.cargo/env' >> /home/me/.bashrc

RUN cargo install eza
RUN cargo install ripgrep
