FROM ubuntu:24.04

RUN apt update
# Install my shell
RUN apt install -y git ninja-build gettext cmake unzip curl build-essential

# Install requirements for nvim build
WORKDIR /tmp

RUN git clone --branch release-0.10 --single-branch https://github.com/neovim/neovim.git

WORKDIR /tmp/neovim
RUN make CMAKE_BUILD_TYPE=Release
RUN make install

# Create my user
RUN useradd -ms /usr/bin/zsh me
# Set workdir to my home directory
USER me
WORKDIR /home/me

# Install rust so that we can use rust tools
ENV PATH="/home/me/.cargo/bin:${PATH}"
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source ~/.cargo/env' >> /home/me/.bashrc

RUN curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh

RUN cargo install eza
RUN cargo install ripgrep
RUN cargo install atuin

RUN set -x; cd "$(mktemp -d)" && \
  OS="$(uname | tr '[:upper:]' '[:lower:]')" && \
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" && \
  KREW="krew-${OS}_${ARCH}" && \
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" && \
  tar zxvf "${KREW}.tar.gz" && \
  ./"${KREW}" install krew
