#!/usr/bin/env bash
# Compose ~/.config/herdr/config.toml from the shared fragment plus this
# platform's [terminal] block.
#
# herdr reads exactly one config.toml and has no include directive, so the
# config cannot be split with a symlink the way the rest of the dotfiles are.
# Keeping the keybindings in one shared fragment and generating the final
# file is the alternative to duplicating them per platform, which is how the
# Linux box silently drifted from the Windows one in the first place.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED="$REPO_DIR/herdr/config.shared.toml"
PLATFORM="$REPO_DIR/herdr/config.linux.toml"
DEST="${XDG_CONFIG_HOME:-$HOME/.config}/herdr/config.toml"

for f in "$SHARED" "$PLATFORM"; do
  [ -f "$f" ] || { echo "missing fragment: $f" >&2; exit 1; }
done

mkdir -p "$(dirname "$DEST")"

# Generated, not linked: warn anyone who opens it looking for the source.
NEW="$(mktemp)"
trap 'rm -f "$NEW"' EXIT
{
  echo "# GENERATED by scripts/install-herdr-config.sh -- do not edit."
  echo "# Edit herdr/config.shared.toml (keys, ui) or herdr/config.linux.toml"
  echo "# (shell), then re-run the script and \`herdr server reload-config\`."
  echo
  cat "$SHARED"
  echo
  cat "$PLATFORM"
} > "$NEW"

# Idempotent: leave the file (and its mtime) alone when nothing changed.
if [ -f "$DEST" ] && cmp -s "$NEW" "$DEST"; then
  echo "herdr config already up to date: $DEST"
  exit 0
fi

# Back up a hand-edited file rather than silently discarding it.
if [ -f "$DEST" ] && ! head -1 "$DEST" | grep -q "^# GENERATED"; then
  cp "$DEST" "$DEST.backup"
  echo "backed up unmanaged config: $DEST.backup"
fi

cp "$NEW" "$DEST"
echo "composed herdr config: $DEST"

# Validate, and apply to a running server if there is one. Neither is fatal:
# herdr may not be installed on every box that runs the dotfiles install.
if command -v herdr >/dev/null 2>&1; then
  herdr config check || true
fi
